### ISSUE TITLE
error: Project ERROR: libqrencode development package not found

### ISSUE THREAD

**Issue by mohsenD98** [woboq/using_the_qt_quick_scene_graph_api#1]
hello . i just downloaded project and opened it with Qt

My Config:
![image](https://user-images.githubusercontent.com/36326627/155619208-963f888e-fd23-4a21-b93b-8c69d14224fb.png)

i keep getting this error:
error: libqrencode development package not found
error: [Makefile:497: Makefile] Error 3

what should i do? and im with ubuntu

**Comment by MidnightCoder-m** [comment]
found solution: 
sudo aptitude install libqrencode-dev

**Comment by ogoffart** [comment]
Note that this repository is not maintained and is just an example made for a talk.  It was made for Qt 5.5 so maybe things will break using Qt6.
